### ISSUE TITLE
Spring Boot throws NullPointerException when try to login with example users.

### ISSUE THREAD

**Issue by mrkmedvedev** [springframeworkguru/springbootwebapp#21]
I've downloaded the sources and try to run it from Spring Tool Suite. In the example provided you created two users (user and admin) which are in the JPA data sources from the beginning of the run of the Spring Boot application. But I found that when trying to running the application without making any modifications to it, it throws an NullPointerException when trying to login from the web interface.

This occurs when running the part6 branch.

**Comment by springframeworkguru** [comment]
I'm unable to recreate the problem. Try running from the command line via Maven. STS is flakey, which is why I wont use it.
