### ISSUE TITLE
PostgreSQL?

### ISSUE THREAD

**Issue by MattMoranJava** [springframeworkguru/springbootwebapp#23]
Hi - I tried to run the Spring Boot app, but it falls over trying to get a connection to PostgreSQL. I thought this was supposed to be running H2? I can see stuff relating to both databases in the code. What's going on?

**Comment by springframeworkguru** [comment]
Opps. Accidently merged a Postgres example into master. Should be good now

**Comment by MattMoranJava** [comment]
Thanks John - much appreciated :-)
